### POST-запрос с валидным токеном и всеми параметрами
POST http://localhost:3000/api/spaceproxy/buyProxy HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF0SWQiOjU0NzczNDExMDcsImlhdCI6MTczNzQ4NDY1NSwiZXhwIjoxNzM3NTA2MjU1fQ.olbXPn5D3IhroP_WYipJ6JEJcigxi57sTJ76iHi8xX8
Content-Type: application/json

{
  "country": "us",
  "period": 5,
  "quantity": 1
}